trainer:
  max_steps: 3760 #20000, to get 40 epochs with batch size 1
  val_check_interval: 93 #1000, every epoch
  check_val_every_n_epoch: ~
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
model:
  class_path: training.linear_semantic.LinearSemantic
  init_args:
    network:
      class_path: models.linear_decoder.LinearDecoder
data:
  class_path: datasets.cityscapes.Cityscapes